#!/usr/bin/env bash
# homelab-tsdb install script.
#
# There's no release pipeline yet, so this builds from source rather than
# downloading a prebuilt binary - Go gets installed via apt if it's missing.
# Once GitHub releases exist, swap the build step for a binary download;
# the detection/systemd/config logic below doesn't need to change.
set -euo pipefail

REPO_URL="${HOMELAB_TSDB_REPO:-https://github.com/BramVH98/homelab-tsdb.git}"
INSTALL_DIR="/usr/local/bin"
BINARY_NAME="homelab-tsdb-logserver"
CONFIG_DIR="/etc/homelab-tsdb"
DATA_DIR="/var/lib/homelab-tsdb"
SERVICE_USER="homelab-tsdb"
BUILD_DIR="$(mktemp -d)"

bold() { printf "\033[1m%s\033[0m\n" "$1"; }
check() { printf "  \033[32m✓\033[0m %s\n" "$1"; }
cross() { printf "  \033[90m✗\033[0m %s (not detected)\n" "$1"; }

trap 'rm -rf "$BUILD_DIR"' EXIT

if [ "$(id -u)" -ne 0 ]; then
    echo "This installer needs root (it installs a systemd service and a system user)."
    echo "Try: curl ... | sudo bash"
    exit 1
fi

bold "homelab-tsdb installer"
echo ""

# --- 1. Ensure Go is available ---
if ! command -v go >/dev/null 2>&1; then
    echo "Go not found - installing via apt..."
    apt-get update -qq
    apt-get install -y -qq golang-go
fi

# --- 2. Get the source and build ---
echo "Fetching source..."
git clone --quiet --depth 1 "$REPO_URL" "$BUILD_DIR/src"
cd "$BUILD_DIR/src"

echo "Building..."
go build -o "$BUILD_DIR/$BINARY_NAME" ./cmd/logserver
install -m 755 "$BUILD_DIR/$BINARY_NAME" "$INSTALL_DIR/$BINARY_NAME"

# --- 3. Detect what's on this machine ---
echo ""
bold "Detected:"

HAS_DOCKER=false
if command -v docker >/dev/null 2>&1; then
    check "Docker"
    HAS_DOCKER=true
else
    cross "Docker"
fi

HAS_APACHE=false
if systemctl is-active --quiet apache2 2>/dev/null || systemctl is-active --quiet httpd 2>/dev/null; then
    check "Apache"
    HAS_APACHE=true
else
    cross "Apache"
fi

HAS_NGINX=false
if systemctl is-active --quiet nginx 2>/dev/null; then
    check "Nginx"
    HAS_NGINX=true
else
    cross "Nginx"
fi

# --- 4. Set up user, directories, config ---
if ! id "$SERVICE_USER" >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
fi

mkdir -p "$CONFIG_DIR" "$DATA_DIR"
chown -R "$SERVICE_USER:$SERVICE_USER" "$DATA_DIR" "$CONFIG_DIR"

ADMIN_PASS="$(head -c 12 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 16)"

if [ ! -f "$CONFIG_DIR/logserver.conf" ]; then
    {
        echo "# homelab-tsdb logserver config - generated by installer"
        echo "addr = :8080"
        echo "auth-user = admin"
        echo "auth-pass = $ADMIN_PASS"
        echo "data = $DATA_DIR/data"
        echo "retention = 720h"
        echo "retention-check = 1h"
        # Syslog is restricted to localhost by default - safe to enable
        # unconditionally, since Docker/Apache/Nginx logs (if wired up)
        # only ever originate from this same machine.
        echo "syslog-addr = :5514"
        echo "syslog-allow = 127.0.0.1/32"
    } > "$CONFIG_DIR/logserver.conf"
    chmod 600 "$CONFIG_DIR/logserver.conf"
    chown "$SERVICE_USER:$SERVICE_USER" "$CONFIG_DIR/logserver.conf"
fi

# --- 5. systemd unit ---
cat > /etc/systemd/system/homelab-tsdb.service << EOF
[Unit]
Description=homelab-tsdb log server
After=network.target

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_USER
ExecStart=$INSTALL_DIR/$BINARY_NAME -config=$CONFIG_DIR/logserver.conf
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$DATA_DIR
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --quiet homelab-tsdb
systemctl restart homelab-tsdb
sleep 1

echo ""
if systemctl is-active --quiet homelab-tsdb; then
    bold "Dashboard available at :8080"
    echo "  user: admin"
    echo "  pass: $ADMIN_PASS"
    echo "  (saved in $CONFIG_DIR/logserver.conf)"
else
    echo "Service failed to start - check: journalctl -u homelab-tsdb -n 50"
    exit 1
fi

echo ""
echo "Next steps for what was detected:"
if [ "$HAS_APACHE" = true ]; then
    echo "  Apache: pipe access logs in with the 'logger' command, e.g.:"
    echo "    CustomLog \"|/usr/bin/logger -n 127.0.0.1 -P 5514 -d -t apache\" combined"
fi
if [ "$HAS_NGINX" = true ]; then
    echo "  Nginx supports syslog natively - add to your config:"
    echo "    access_log syslog:server=127.0.0.1:5514,tag=nginx combined;"
fi

if [ "$HAS_DOCKER" = true ]; then
    echo "  Docker: configuring syslog as the default log driver for new containers..."
    python3 << 'PYEOF'
import json, os, time, shutil

path = "/etc/docker/daemon.json"
existing = {}

if os.path.exists(path):
    backup = f"{path}.bak-{time.time_ns()}"
    shutil.copy2(path, backup)
    print(f"    backed up existing config to {backup}")
    try:
        with open(path) as f:
            existing = json.load(f)
    except (json.JSONDecodeError, ValueError):
        print(f"    WARNING: existing {path} wasn't valid JSON - starting fresh (original is backed up above)")
        existing = {}

existing["log-driver"] = "syslog"
existing["log-opts"] = {
    "syslog-address": "udp://127.0.0.1:5514",
    "tag": "{{.Name}}",
}

os.makedirs(os.path.dirname(path), exist_ok=True)
with open(path, "w") as f:
    json.dump(existing, f, indent=2)
    f.write("\n")
print(f"    updated {path}")
PYEOF
    echo "  NOTE: this only affects NEW containers. Already-running containers"
    echo "  need to be recreated (docker compose up -d --force-recreate, or"
    echo "  docker stop/rm + run again) to pick up the new default log driver."
    if command -v systemctl >/dev/null 2>&1 && systemctl is-active --quiet docker 2>/dev/null; then
        systemctl restart docker
        echo "  Docker restarted to apply the change."
    fi
fi

if [ "$HAS_APACHE" = true ] || [ "$HAS_NGINX" = true ]; then
    echo ""
    echo "  Apache/Nginx config isn't edited automatically - their config"
    echo "  layout varies too much between systems to safely guess at, so"
    echo "  the one-liner above is copy-pasteable into your existing config."
fi